### ISSUE TITLE
x64環境でProgram Files以下のVirtualboxへのリンクをドラッグアンドドロップすると" (x86)"が付加された無効なパスになる

### ISSUE THREAD

**Issue by geotrader** [crftwr/clnch#5]
### Issue type
- Bug report

### Versions
- clnch
    - 3.33
- virtualBox
    - 5.2.0
- OS
    - Windows 10 64bit Pro Build15063

### comment
e527179762d37f2fc33e1867847919304dc9a895で修正されているのかもしれませんが、よくわからないので報告します
もし解決予定でしたらクローズ頂けると助かります
3.34リリース後解消されていれば勝手にクローズします

### Description:
1. VirtualboxでBoxを右クリックからリンクを作成する

    リンク先 "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" --comment "arch" --startvm "26c5dccd-8c27-4953-bbf8-07fc90010ff0"
    作業フォルダ "C:\Program Files\Oracle\VirtualBox"

1. 上の情報を持ったアイコンをclnchにドラッグアンドドロップする
1.以下の画像のように" (x86)”が付加されてしまう
![add_command_with_drag_and_drop](https://user-images.githubusercontent.com/15902749/32421489-8507ae0a-c2dc-11e7-8375-27de5927da51.png)

### Expected behavior
リンク先と同等のものがclnchに登録される

**Comment by crftwr** [comment]
VirtualBox ver 6.0.0 で試したのですが、VirtualBox でショートカットを作ったとき、ショートカットのパスが (x86) 付きになってしまうようです。
例 : "C:\Program Files (x86)\Oracle\VirtualBox\VirtualBox.exe" --comment "Linux" --startvm "{807c9bbb-b11a-435b-8e16-8c6513283a10}"

VirtualBox側の問題としてCloseします。
